// src/app/play/game-sense/lib/scoring.ts

import { GAMES, type GameSenseGame } from '../data/games'

// Precomputed semantic rankings (generated by scripts/generate-rankings.mjs).
// When null, falls back to metadata-based distance ranking.
import { RANKINGS } from '../data/rankings'

// ── Fallback distance metric ────────────────────────────────────────────────

function jaccardDistance(a: string[], b: string[]): number {
  const setA = new Set(a)
  const setB = new Set(b)
  const intersection = [...setA].filter((x) => setB.has(x)).length
  const union = new Set([...setA, ...setB]).size
  if (union === 0) return 0
  return 1 - intersection / union
}

const PEGI_ORDER = [3, 7, 12, 16, 18]
function pegiDistance(a: number, b: number): number {
  const idxA = PEGI_ORDER.indexOf(a)
  const idxB = PEGI_ORDER.indexOf(b)
  if (idxA === -1 || idxB === -1) return 1
  return Math.abs(idxA - idxB) / (PEGI_ORDER.length - 1)
}

function rawDistance(guess: GameSenseGame, answer: GameSenseGame): number {
  const genreScore = jaccardDistance(guess.genres, answer.genres) * 300
  const yearScore = Math.min(Math.abs(guess.year - answer.year), 200)
  const platformScore = jaccardDistance(guess.platforms, answer.platforms) * 150
  const multiplayerScore = guess.multiplayer === answer.multiplayer ? 0 : 100
  const pegiScore = pegiDistance(guess.pegi, answer.pegi) * 150
  const guessOC = guess.openCritic ?? 50
  const answerOC = answer.openCritic ?? 50
  const ocScore = (Math.min(Math.abs(guessOC - answerOC), 100) / 100) * 100

  return genreScore + yearScore + platformScore + multiplayerScore + pegiScore + ocScore
}

function fallbackRank(guess: GameSenseGame, answer: GameSenseGame): number {
  const guessDistance = rawDistance(guess, answer)
  let closerCount = 0
  for (const game of GAMES) {
    if (game.id === answer.id || game.id === guess.id) continue
    if (rawDistance(game, answer) < guessDistance) closerCount++
  }
  return closerCount + 2
}

// ── Public API ──────────────────────────────────────────────────────────────

/**
 * Calculate the rank of a guessed game relative to the answer.
 * Returns 1 if correct (same game), otherwise 2–N where N = total games.
 * Rank 2 = most similar game, rank N = least similar.
 *
 * Uses precomputed semantic rankings if available, otherwise falls back
 * to a metadata-based distance metric.
 */
export function calculateRank(
  guess: GameSenseGame,
  answer: GameSenseGame,
): number {
  if (guess.id === answer.id) return 1

  if (RANKINGS && RANKINGS[answer.id]) {
    const idx = RANKINGS[answer.id].indexOf(guess.id)
    return idx === -1 ? GAMES.length : idx + 2
  }

  return fallbackRank(guess, answer)
}
